version: "3.8"

services:
  react-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: osint-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
    networks:
      - backend-net

networks:
  backend-net:

volumes:
  postgres_data:
  docker_logs: